 
import turtle

def setup():
    turtle.screensize(300, 200)
    turtle.pensize(2)
    turtle.colormode(255)
    turtle.color((255,150,182),"pink")
    turtle.setup(840,500)
    turtle.speed(40)

def nose():
    turtle.pu()
    turtle.goto(-100,100)
    turtle.pd()
    turtle.seth(-30)
    turtle.begin_fill()
    a=0.4
    for i in range(120):
       if 0<=i<30 or 60<=i<90:
           a=a+0.08
           turtle.lt(3)
           turtle.fd(a)
       else:
           a=a-0.08
           turtle.lt(3)
           turtle.fd(a)
    turtle.end_fill()
    turtle.pu()
    turtle.seth(90)
    turtle.fd(25)
    turtle.seth(0)
    turtle.fd(10)
    turtle.pd()
    turtle.pencolor(255,150,182)
    turtle.seth(10)
    turtle.begin_fill()
    turtle.circle(8)
    turtle.color(150,80,40)
    turtle.end_fill()
    turtle.pu()
    turtle.seth(0)
    turtle.fd(20)
    turtle.pd()
    turtle.pencolor(255,150,182)
    turtle.seth(10)
    turtle.begin_fill()
    turtle.circle(8)
    turtle.color(160,82,45)
    turtle.end_fill()

def head():
    turtle.color((255,150,182),"pink")
    turtle.pu()
    turtle.seth(90)
    turtle.fd(41)
    turtle.seth(0)
    turtle.fd(0)
    turtle.pd()
    turtle.begin_fill()
    turtle.seth(180)
    turtle.circle(300,-30)
    turtle.circle(100,-60)
    turtle.circle(80,-100)
    turtle.circle(150,-20)
    turtle.circle(60,-95)
    turtle.seth(161)
    turtle.circle(-300,15)
    turtle.pu()
    turtle.goto(-100,100)
    turtle.pd()
    turtle.seth(-30)
    a=0.4
    for i in range(60):
       if 0<=i<30 or 60<=i<90:
           a=a+0.08
           turtle.lt(3) #向左转3度
           turtle.fd(a) #向前走a的步长
       else:
           a=a-0.08
           turtle.lt(3)
           turtle.fd(a)
    turtle.end_fill()

def ear():
    turtle.color((255,150,182),"pink")
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-7)
    turtle.seth(0)
    turtle.fd(70)
    turtle.pd()
    turtle.begin_fill()
    turtle.seth(100)
    turtle.circle(-50,50)
    turtle.circle(-10,120)
    turtle.circle(-50,54)
    turtle.end_fill()
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-12)
    turtle.seth(0)
    turtle.fd(30)
    turtle.pd()
    turtle.begin_fill()
    turtle.seth(100)
    turtle.circle(-50,50)
    turtle.circle(-10,120)
    turtle.circle(-50,56)
    turtle.end_fill()

def eye():
    turtle.color((255,150,182),"white")
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-20)
    turtle.seth(0)
    turtle.fd(-95)
    turtle.pd()
    turtle.begin_fill()
    turtle.circle(25)
    turtle.end_fill()
    turtle.color("black")
    turtle.pu()
    turtle.seth(90)
    turtle.fd(12)
    turtle.seth(0)
    turtle.fd(-3)
    turtle.pd()
    turtle.begin_fill()
    turtle.circle(3)
    turtle.end_fill()
    turtle.color((255,150,182),"white")
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-25)
    turtle.seth(0)
    turtle.fd(40)
    turtle.pd()
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.color("black")
    turtle.pu()
    turtle.seth(90)
    turtle.fd(12)
    turtle.seth(0)
    turtle.fd(-3)
    turtle.pd()
    turtle.begin_fill()
    turtle.circle(3)
    turtle.end_fill()

def cheek():
    turtle.color((255,130,132))
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-95)
    turtle.seth(0)
    turtle.fd(65)
    turtle.pd()
    turtle.begin_fill()
    turtle.circle(30)
    turtle.end_fill()

def mouth():
    turtle.color(230,60,38)
    turtle.pu()
    turtle.seth(90)
    turtle.fd(15)
    turtle.seth(0)
    turtle.fd(-100)
    turtle.pd()
    turtle.seth(-80)
    turtle.circle(30,40)
    turtle.circle(40,80)

def body():
    turtle.color("red",(255,90,65))
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-20)
    turtle.seth(0)
    turtle.fd(-78)
    turtle.pd()
    turtle.begin_fill()
    turtle.seth(-130)
    turtle.circle(100,10)
    turtle.circle(300,30)
    turtle.seth(0)
    turtle.fd(230)
    turtle.seth(90)
    turtle.circle(300,30)
    turtle.circle(100,3)
    turtle.color((255,150,180),(255,90,90))
    turtle.seth(-135)
    turtle.circle(-80,63)
    turtle.circle(-150,24)
    turtle.end_fill()

def hand():
    turtle.color((255,150,182))
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-40)
    turtle.seth(0)
    turtle.fd(-27)
    turtle.pd()
    turtle.seth(-160)
    turtle.circle(300,15)
    turtle.pu()
    turtle.seth(90)
    turtle.fd(15)
    turtle.seth(0)
    turtle.fd(0)
    turtle.pd()
    turtle.seth(-10)
    turtle.circle(-20,90)
    turtle.pu()
    turtle.seth(90)
    turtle.fd(30)
    turtle.seth(0)
    turtle.fd(237)
    turtle.pd()
    turtle.seth(-20)
    turtle.circle(-300,15)
    turtle.pu()
    turtle.seth(90)
    turtle.fd(20)
    turtle.seth(0)
    turtle.fd(0)
    turtle.pd()
    turtle.seth(-170)
    turtle.circle(20,90)

def foot():
    turtle.pensize(14)
    turtle.color((240,128,128))
    turtle.pu()
    turtle.seth(90)
    turtle.fd(-75)
    turtle.seth(0)
    turtle.fd(-180)
    turtle.pd()
    turtle.seth(-90)
    turtle.fd(40)
    turtle.seth(-180)
    turtle.color("black")
    turtle.pensize(15)
    turtle.fd(20)
    turtle.pensize(10)
    turtle.color((255,128,128))
    turtle.pu()
    turtle.seth(90)
    turtle.fd(40)
    turtle.seth(0)
    turtle.fd(90)
    turtle.pd()
    turtle.seth(-90)
    turtle.fd(40)
    turtle.seth(-180)
    turtle.color("black")
    turtle.pensize(15)
    turtle.fd(20)

def tail():
    turtle.pensize(2)
    turtle.color((255,150,182))
    turtle.pu()
    turtle.seth(90)
    turtle.fd(70)
    turtle.seth(0)
    turtle.fd(95)
    turtle.pd()
    turtle.seth(0)
    turtle.circle(70,20)
    turtle.circle(10,330)
    turtle.circle(70,30)
    turtle.done()

def main():
    setup()
    nose()
    head()
    ear()
    eye()
    cheek()
    mouth()
    body()
    hand()
    foot()
    tail()

if __name__ == '__main__':
  main()